name: Build and Test

permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo Checking out code; sleep 5            
      - name: Build and run unit/integration tests
        run: echo Building and running tests; sleep 5
        
  component-tests:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Setup test infrastructure
        run: echo Setting up infrastructure; sleep 5            
      - name: Running component tests
        run: echo Running component tests; sleep 5
        
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Static code analysis
        run: echo Analysing code; sleep 10
