name: Delivery Pipeline

permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:  
  delivery-pipeline:
    uses: anders-olofsson/gh-actions-test-shared/.github/workflows/delivery-pipeline.yaml@main
    with:
      version: ${{ github.sha }}
      dummy: abc
