# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [Build and Test]
    types:
      - completed

  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Test
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "Event Context:"
          echo "$EVENT_CONTEXT"
