name: Rollback Deployment

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      rollback-app-a:
        description: Rollback App A to previous version
        type: boolean
        default: "false"
      rollback-app-b:
        description: Rollback App B to previous version
        type: boolean
        default: "false"
      rollback-app-c:
        description: Rollback App C to previous version
        type: boolean
        default: "false"

jobs:
  rollback-app-a:
    if: ${{ github.event.inputs.rollback-app-a == 'true' }}
    uses: anders-olofsson/gh-actions-test-shared/.github/workflows/deploy.yaml@main
    with:
      image: app-a-image-repo
      version: ${{ github.sha }}

  rollback-app-b:
    if: ${{ github.event.inputs.rollback-app-b == 'true' }}
    uses: anders-olofsson/gh-actions-test-shared/.github/workflows/deploy.yaml@main
    with:
      image: app-b-image-repo
      version: ${{ github.sha }}

  rollback-app-c:
    if: ${{ github.event.inputs.rollback-app-c == 'true' }}  
    uses: anders-olofsson/gh-actions-test-shared/.github/workflows/deploy.yaml@main
    with:
      image: app-c-image-repo
      version: ${{ github.sha }}
